server:
  port: 8080

spring:
  application:
    name: currency-exchange-app-lombok
  
  r2dbc:
    url: r2dbc:h2:mem:///testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    pool:
      enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console

  security:
    user:
      name: admin
      password: admin123

  sql:
    init:
      mode: always      # ✅ Para que siempre se ejecuten schema.sql y data.sql
      platform: h2
      schema-locations: classpath:schema.sql

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
